### ISSUE TITLE
Runner throws an error in 7.3rc

### ISSUE THREAD

**Issue by KevinJump** [aaronpowell/Chauffeur#26] opened 2015-08-26 12:03 UTC
_I know it's a Release Candidate - I therefore accept if no support is offered_

Running Chauffeur.Runner on Umbraco 7.3 results in an error. 

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Chauffeur.DependencyBuilders.MappingResolversBuilder.SetupMappingResolver()
   at Chauffeur.DependencyBuilders.MappingResolversBuilder.Build(IContainer container)
   at Chauffeur.ShittyIoC.RegisterFrom[T]()
   at Chauffeur.Host.UmbracoHost..ctor(TextReader reader, TextWriter writer)
   at Chauffeur.Runner.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, String[] args)
   at Chauffeur.Runner.Program.Main(String[] args)`

I've looked at the Morton's Console example (https://github.com/sitereactor/umbraco-console-example) and that throws a similar error, so i think something has changed in the BootManager ?

**Comment by aaronpowell** [comment] 2015-08-26 12:29
I haven't looked at 7.3 yet so yeah there's a chance that there's a breaking change `MappingResolver` type and the way it's exposed.

Which version of Chauffeur are you using?

**Comment by KevinJump** [comment] 2015-08-26 14:00
Hi 

It was the latest from nuget 0.5.1.

**Comment by aaronpowell** [comment] 2015-08-26 22:47
Cool, I'll look into the problem and update this issue

**Comment by aaronpowell** [comment] 2015-08-26 23:41
The problem is that in [this commit](https://github.com/umbraco/Umbraco-CMS/commit/1cb0cd296c98eaf901993c9a404647e858bf4c92) the MappingResolver constructor signature was changed so my reflection no longer works. I'll have a look into a way I can work around this better.

**Comment by KevinJump** [comment] 2015-08-27 07:52
yeah, I did have a look, but to be honest It's way beyond me. 

I've been flicking between this code and Morton's I get the stuff in program.cs redirecting the configs and stuff, but then all the reflection stuff throws me :) 

it 7.3 it looks like you can just call the CoreBootManager (with the DataDirectory and config set) from a basically empty ApplicationBase class. but I suspect there are many subtle and important things i am missing. Would love to understand a bit more, I am sure if i got this reflection lark, I would be better at loads of thing :)

**Comment by aaronpowell** [comment] 2015-08-27 08:26
Yeah I didn't use the `BootManager` to setup my dependencies and the primary reason was that if I did it I would have a hard time exposing them via the DI container, but I might have to look at it again.

I think I know another way I could attempt it though, I'll have a look when I have some time

**Comment by aaronpowell** [comment] 2015-08-27 22:59
I had a look into this last night and managed to fix the above error against 7.3 but found more errors. I'm going to have a look at whether I can use the `BootManager` instead, but that'll probably not be until the weekend

**Comment by aaronpowell** [comment] 2015-08-28 06:22
I think I have this sorted out now by swapping to the `BootManager`. Once the current AppVoyer build completes `0.6.0-beta1` will be on NuGet if you can test it that'd be ace

**Comment by KevinJump** [comment] 2015-08-28 07:20
cool, that works. 

Occasionally i get an error when quitting... 

> Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
>   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
>   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
>   at Microsoft.Win32.SafeNativeMethods.ReleaseSemaphore(SafeWaitHandle handle, Int32 releaseCount, Int32& previousCount)
>   at System.Threading.Semaphore.Release(Int32 releaseCount)
>   at System.Threading.Semaphore.Release()
>   at Umbraco.Core.AsyncLock.NamedSemaphoreReleaser.Finalize()

but i think that's umbraco refusing to let go.

**Comment by aaronpowell** [comment] 2015-09-03 09:32
I haven't been able to repo that yet, but I'm just releasing `0.6.0` which supports 7.3-RC

**Comment by KevinJump** [comment] 2015-09-03 09:45
yeah, I think you just run the command go off and do something else and come back 5-10 mins later and then *sometimes* it will throw the error

Cool, I have a uSync deliverable doing import and export of almost everything via chauffeur now for 7.3-RC https://github.com/KevinJump/uSync3.0/tree/master/Jumoo.uSync.Migrations 

looking at snapshots / change-sets next

**Comment by aaronpowell** [comment] 2015-09-03 09:47
you know, we really should have collaborated on this, as I'm just about ready to release https://github.com/aaronpowell/chauffeur.usync which creates `delivery` scripts :stuck_out_tongue:

**Comment by KevinJump** [comment] 2015-09-03 09:55
yeah I got tied up in uSync 3 quite a bit :smile: It is using all the newer v7.3 api improvements (there are a alot of little ones) so it's going to track things like renames and deletes a lot better, lots of internal ID mapping that the old uSync couldn't do is now in v7.3,

also v3 has separated out the disk bit from the serialize/deserialize bit, so you don't have to do all that folder juggling, you can just tell usync to push an export to a specified folder and it will.

**Comment by KevinJump** [comment] 2015-09-03 09:57
of course the f# stuff is way neater - I might just concentrate on getting the migration classes sorted so you can call them :)

**Comment by aaronpowell** [comment] 2015-09-03 10:03
My plan was to rely on uSync to generate the XML files and standard Umbraco packaging engine to import. There's a few custom exports that uSync does that I was going to delegate back.

I've always tried to keep it as using as many of the Umbraco API's as possible, so I know that I'm not writing my own bugs :stuck_out_tongue:

**Comment by KevinJump** [comment] 2015-09-03 10:08
yeah, the issue with the packaging api is that it is written to be non destructive, So it doesn't change things if they already exist - so for example it will add new properties to a doctype but it won't alter existing ones. it doesn't move things between tabs, or delete properties if they are removed. 

uSync mainly uses the packaging api to do the initial import and then does all the additional changes with the result, so it changes properties, deletes / renames tabs etc. It means a usync change is a change, not a merge of existing and new settings. It's subtle (and what makes the code a real pain), but it means you get exactly the same result at both ends of a sync.

**Comment by aaronpowell** [comment] 2015-09-03 10:18
Yeah I know about the limitation with packaging but I didn't know uSync worked around it. Might have to have a think about how to best integrate.

**Comment by aaronpowell** [comment] 2016-12-21 21:43
I'm going to close this as it's related to a pre-release Umbraco version (that is now outdated)

**Closed by aaronpowell** 2016-12-21 21:43 UTC
