### ISSUE TITLE
Support newer versions of umbraco

### ISSUE THREAD

**Issue by slahn** [aaronpowell/Chauffeur#46] opened 2017-05-16 13:06 UTC
Hi,
Chauffeur looks really interesting, but doesn't work with current versions of Umbraco.

It seems like keeping one version of Chauffeur working cross different versions of umbraco 7.x will be quite hard. I'm not sure how to solve this.

Anyway, I've tried to update Chauffeur to work with 7.6 in https://github.com/slahn/Chauffeur/tree/umbraco-7.6
Still a couple of tests that don't pass - they seem to fail because of actual changes in umbraco.

**Comment by aaronpowell** [comment] 2017-05-16 22:37
Hey @slahn, I haven't had time to look at Chauffeur against v7.6 so thanks for starting up on it 😄.

You mention that some tests fail, are they unit or integration tests, and which ones in particular?

**Comment by slahn** [comment] 2017-05-18 07:30
The failed tests are integration tests,
Install deliverable fails because the expected tables in the database doesn't match.
Importing document types fails with varying errors - sometimes it doesn't find the document type, sometimes an expected '1050' is actually '1060'.

I've also done some semi-hackish things to the integration test project in order to make SQL server CE load properly - so watch out for that...

**Comment by aaronpowell** [comment] 2017-05-22 11:20
Ah a change in DB schema would likely give me issues. If I get some time over the rest of the week I'll have a look at it too.

**Comment by aDotNetDeveloper** [comment] 2017-05-23 04:37
This is what I'm getting with 7.6.1, hope this helps somewhat

Unhandled Exception: System.TypeLoadException: Method 'FetchPackageFile' in type 'Chauffeur.Services.OverridingPackaging
Service' from assembly 'Chauffeur, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by aaronpowell** [comment] 2017-05-23 05:08
It would seem that they have added a new member to the `IPackagingService` interface which I (naturally) haven't previously had.

This is the danger of interfaces, you have to remember that they are not great for backwards compatibility. I'll have to put in some proper effort to fix it by the looks of it 😛 .

**Comment by aaronpowell** [comment] 2017-05-23 05:09
Just tagging in @shazwazza to surface the above issue.

**Comment by Shazwazza** [comment] 2017-05-23 05:16
Indeed they are not good for compatibility and Umbraco is already riddled with difficulties in maintaining compatibility. This document has existed for a very long time https://our.umbraco.org/Documentation/Development-Guidelines/breaking-changes

We add to service interfaces all of the time because you cannot actually implement and use these interfaces directly in Umbraco because we don't allow that to happen. If these things are being used externally to the website (i.e. unit tests, etc...) then you'll need to rebuild.

**Comment by slahn** [comment] 2017-05-23 05:24
This is one of the errors fixed in my branch, in the first commit: https://github.com/slahn/Chauffeur/commit/ec226259d383a0cf8df39279c5374124692ab49b

Sorry if my comment made it seem like I just rebuilt and ended up with the two integration error tests, I had to do a bit of work before I got there...

**Comment by Shazwazza** [comment] 2017-05-23 05:31
Yup - sorry my phrasing wasn't exactly clear, because these interfaces are susceptible to changes, packages that actively use them and implement them would need to rebuild/fix and release new versions.

**Comment by aaronpowell** [comment] 2017-05-23 06:21
Yeah I get that @shazwazza, and I'm very much skirting on the fringes of what the API was intended for ;).

It's just that having breaking changes at an `interface` level makes multi-targeting a real challenge :(

**Comment by Shazwazza** [comment] 2017-05-23 06:21
Then don't multi-target and release a new major version

**Comment by aaronpowell** [comment] 2017-05-23 06:29
I could make a similar point about breaking API surface area 😛, but disregard for backwards compatibility isn't really viable for a tool like Chauffeur. I want to ensure that I provide features to people without forcing them to upgrade their Umbraco instance too, or inversely lock people to 'older' versions.

**Comment by Shazwazza** [comment] 2017-05-23 06:48
I know but it is what it is. So you can either go down the reflection downward spiral or you can release a major version and urge people to upgrade their Umbraco installs to maintain support, or maintain multiple major versions.

**Comment by aaronpowell** [comment] 2017-05-23 06:50
I already have some awesome reflection: https://github.com/aaronpowell/Chauffeur/blob/master/Chauffeur/Services/OverridingPackagingService.cs#L232-L245 and https://github.com/aaronpowell/Chauffeur/blob/master/Chauffeur/Deliverables/ContentTypeDeliverable.cs#L148-L172

Hmm I should see if that code is still needed

**Comment by aaronpowell** [comment] 2017-05-23 06:52
"You either die a hero or live long enough to write reflection code that hacks internal members"

😛 :trollface:

**Comment by aaronpowell** [comment] 2017-05-23 11:41
Hey all, I've done some refactoring to make Chauffeur work with Umbraco 7.6, or at least, I think it does (haven't got time to do anything more than my integration tests 😛).

If you're able to test for me here's the NuGet packages:

Chauffeur Runner: https://www.nuget.org/packages/Chauffeur.Runner/0.10.0-umbraco-7-59
Chauffeur: https://www.nuget.org/packages/Chauffeur/0.10.0-umbraco-7-59

They are pre-release packages so you'll need to be explicit in installing them.

**Comment by dinc5150** [comment] 2017-05-23 13:59
Just gave it a quick spin and worked much better on 7.6.1! Thanks @aaronpowell

**Comment by aaronpowell** [comment] 2017-05-24 01:17
@dinc5150 thanks for the feedback :)

**Comment by rsoeteman** [comment] 2017-05-24 07:08
Besides changes in services make sure to check contentpicker2 en mediapicker2 that is using UDI instead of integer ID's now.

**Comment by aaronpowell** [comment] 2017-05-24 23:13
Thanks @rsoeteman, shouldn't be a problem for me as I don't do anything specific with the editors

**Comment by aDotNetDeveloper** [comment] 2017-06-09 02:33
looks good on 7.5.x too

**Comment by aaronpowell** [comment] 2017-06-09 02:43
Sounds like this is a go for cutting a release 😁

**Comment by dinc5150** [comment] 2017-06-09 03:40
Just before you do... I've been meaning to get back to you about updating user passwords. It hasn't worked for me, the couple of times that I've tried it. I'll have a check shortly and get back to you with better details! Just wanted to grab you before the release

**Comment by dinc5150** [comment] 2017-06-09 06:52
OK, so have just had a chance to test on a Umbraco 7.6.1 install. 

The command:
`user change-password [USERNAME] [PASSWORD]`

Throws: `Error running the current deliverable 'user': This provider does not support manually changing the password` 

`user change-name [USERNAME] [NEW USERNAME]` seems to work OK

**Comment by aaronpowell** [comment] 2017-06-09 06:52
Sure thing @dinc5150 :)

**Comment by aaronpowell** [comment] 2017-06-09 06:53
Curious... I wonder what changed. Will look into my test coverage

**Comment by aDotNetDeveloper** [comment] 2017-06-09 07:18
strange, I ran this today on 7.5.x and this is the delivery

install y
user change-password admin foobah
user change-loginname admin fooadmin

**Comment by dinc5150** [comment] 2017-06-09 08:59
Just tried on a blank install of 7.6.3 and same issue. 

If its any help, this is the culprit - https://github.com/umbraco/Umbraco-CMS/blob/9badb35c054ecc91630b69b1b6753c78427cb4a6/src/Umbraco.Core/Security/MembershipProviderBase.cs#L315 

The history on the file shows some changes in the resetting of passwords recently which is probably whats causing it.

**Comment by aaronpowell** [comment] 2017-06-10 02:09
Nice find @dinc5150.

I think in the past I use to have it require you to set the current password, but must've dropped it. I'll include a fix for that too.

**Comment by aaronpowell** [comment] 2017-06-10 02:22
Well here's the fun fact, I use `IUserService.SavePassword` which hits this line: https://github.com/umbraco/Umbraco-CMS/blob/172ef8c379894023f25cceacc7db6839906c164c/src/Umbraco.Core/Services/UserService.cs#L271 and notice is sends a blank password.

The provider that's in use then doesn't allow you to set with blank passwords and that exception is thrown.

*sigh*

**Comment by aaronpowell** [comment] 2017-06-10 02:53
Ok, I think I've come to the crux of it, the code I have in there _does work_ and the membership provider works as expected.

Where you'll hit an error is that there is a config property you can set on the provider to prevent password changes without providing the *current* password. It comes down to [this line of code](https://github.com/umbraco/Umbraco-CMS/blob/172ef8c379894023f25cceacc7db6839906c164c/src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs#L68), so if you have `allowManuallyChangingPassword=false` in your `web.config` against the `UsersMembershipProvider` you'll not be able to change it via Chauffeur.

I'm going to put a `catch` for that exception and provide better feedback to the users, but I need to make lunch now, so keep an eye on the working branch I have linked 😉.

**Comment by aaronpowell** [comment] 2017-06-10 12:35
Ok, I've added a new error message that should explain the problem you're having with changing password.

I've created a build that contains it, but seems my NuGet.org account has a problem and I can't push releases. You can manually download the build to test from here: https://ci.appveyor.com/project/aaronpowell/chauffeur/build/0.10.0-umbraco-7-61/artifacts

**Comment by dinc5150** [comment] 2017-06-12 11:49
Thanks @aaronpowell . Just change the config setting and it allowed me to update the password.

**Comment by dinc5150** [comment] 2017-06-12 12:05
FYI: Tested out the new version and worked perfectly

**Comment by aaronpowell** [comment] 2017-06-12 22:46
Once I get my AppVeyor issue sorted I'll cut a new release

**Comment by aDotNetDeveloper** [comment] 2017-07-02 12:20
Hi Aaron,

whats the status of a new release ?  I intend to include this in a migration release this coming week.

regards
Wayne

**Comment by aaronpowell** [comment] 2017-07-02 23:25
@aDotNetDeveloper I think AppVeyor is fixed so I've just merged in, but I'll check and if not I'll manually upload the release.

**Comment by aDotNetDeveloper** [comment] 2017-07-02 23:31
thanks,  a pre-release will work just as well

**Comment by aaronpowell** [comment] 2017-07-02 23:32
@aDotNetDeveloper 💥 https://www.nuget.org/packages/Chauffeur/0.10.0

**Comment by aaronpowell** [comment] 2017-07-02 23:33
Closing as we now support 7.6 😀.

**Closed by aaronpowell** 2017-07-02 23:33 UTC
